### ISSUE TITLE
Implementar @angular/router

### ISSUE THREAD

**Issue by poloagustin** [jorgeucano/bootcamp#1]
Angular 2 ya tiene un router que depreca a la primer version. 
Esta basado en [https://github.com/ngrx/router](url)
Que te parece si dejamos la app implementando esta ultima version?

**Comment by jorgeucano** [comment]
ya esta implementado :D el ultimo push tiene implementado ngrx router

**Comment by poloagustin** [comment]
Perdon, quizas me exprese mal.

Me refiero a que el equipo de angular 2 publico el siguiente npm: [https://www.npmjs.com/package/@angular/router](url)

Ese npm esta basado en [https://www.npmjs.com/package/@ngrx/router](url)

Una explicacion del proceso de ruteo en ng2 [https://github.com/angular/angular/tree/master/modules/%40angular/router](url)
